// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package main

var TableNames = struct {
	Categories       string
	Recipes          string
	Reports          string
	SchemaMigrations string
	Users            string
}{
	Categories:       "categories",
	Recipes:          "recipes",
	Reports:          "reports",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
