no-tests = true
wipe = true 


templates = [
  "api/internal/infra/templates/main",
  "api/internal/infra/template/test",
 
]


[mysql]
  dbname     = "test"
  host       = "127.0.0.1"
  port       = 3306
  user       = "root"
  pass       = "pass"
  sslmode    = "false"
