// Code generated by SQLBoiler 4.6.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package datamodel

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Categories", testCategoriesUpsert)

	t.Run("Recipes", testRecipesUpsert)

	t.Run("Reports", testReportsUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Users", testUsersUpsert)
}
